version: '2'
services:

  cre-glue:
    image: credocker/creglue:2018.0
    container_name: creglue
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro

  cre-proxy:
    image: credocker/creproxy:2018.0
    container_name: creproxy
    environment:
      ADMIN_EMAIL: michael.kahle@yahoo.de
      CRE_DOMAIN: localhost
      CRE_EMPTY_SUBDOMAIN: www
      CRE_DEVELOPMENT: dev 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./volumes/certs:/etc/letsencrypt"
    volumes_from:
      - cre-glue

  cre-nginx-php:
   image: credocker/crenginxphp:2018.0
   container_name: crenginxphp
   environment: 
     CRE_SUBDOMAIN: www
     CRE_PHP_ROOT: www/htdocs
     SQLITE_DB: lite
   volumes_from:
    - cre-php
    - cre-glue

  cre-php:
   image: credocker/crephp:2018.0
   container_name: crephp
   environment:
     CRE_NGINX: crenginxphp
   volumes:
      - ./volumes/www/htdocs:/cre/www/htdocs
      - ./volumes/www/sqlite:/cre/www/sqlite
   volumes_from:
    - cre-glue

# docker-compose  --file dc-local.yml up -d
